version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/var/lib/powerBot/config
      - ./data:/var/lib/powerBot/data
    environment:
      # CONF_PATH: '/some/path/'
      # DATA_PATH: '/some/path/'
      TZ: 'Europe/Vienna'
    restart: unless-stopped
