version: '3'
services:
  app:
    image: ghcr.io/0xk1f0/powerbot:master
    volumes:
      - ./config:/var/lib/powerBot/config
      - ./data:/var/lib/powerBot/data
    environment:
      # CONF_PATH: '/some/path/' # path to config files folder
      # DATA_PATH: '/some/path/' # path to data cache folder
      # DS_PATH: '/some/path/' # path to downscaler binary
      TZ: 'Europe/Vienna'
    restart: unless-stopped
